version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
    target-branch: main
  - package-ecosystem: 'composer'
    directory: '/'
    schedule:
      interval: 'weekly'
    ignore:
      - dependency-name: "ralphjsmit/laravel-glide"
    target-branch: main
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'weekly'
    target-branch: main
