version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'monthly'
    target-branch: main

  - package-ecosystem: 'composer'
    directory: '/'
    schedule:
      interval: 'monthly'
    ignore:
      - dependency-name: "ralphjsmit/laravel-glide"
      - dependency-name: '*'
        update-types:
          - 'version-update:semver-major'
    target-branch: main

  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'monthly'
    target-branch: main
