name: Auto Tag and Release

on:
  workflow_dispatch:

  pull_request:
    types: [closed]
    branches:
      - main
    paths-ignore:
      - '.github/**'

jobs:
  release:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Get Token
        id: get_workflow_token
        uses: peter-murray/workflow-application-token-action@v4
        with:
          application_id: ${{ vars.FUELVIEWS_BOT_APP_ID }}
          application_private_key: ${{ secrets.FUELVIEWS_BOT_APP_PRIVATE_KEY }}

      - uses: actions/checkout@v4
        with:
          ref: 'main'
          fetch-depth: '0'
          token: ${{ steps.get_workflow_token.outputs.token }}

      - name: Bump version and push tag
        id: bump_version
        uses: anothrNick/github-tag-action@1.71.0
        env:
          GITHUB_TOKEN: ${{ steps.get_workflow_token.outputs.token }}
          DEFAULT_BUMP: patch
          WITH_V: true
          RELEASE_BRANCHES: main

      - name: Generate Release Notes
        id: generate_release_notes
        uses: actions/github-script@v6
        with:
          result-encoding: string
          script: |
            const { data } = await github.request('POST /repos/{owner}/{repo}/releases/generate-notes', {
              owner: context.repo.owner,
              repo: context.repo.repo,
              tag_name: '${{ steps.bump_version.outputs.new_tag }}',
              target_commitish: 'main',
            });
            return data.body;

      - name: Update Changelog
        uses: stefanzweifel/changelog-updater-action@v1
        with:
          latest-version: ${{ steps.bump_version.outputs.new_tag }}
          release-notes: ${{ steps.generate_release_notes.outputs.result }}

      - name: Commit updated CHANGELOG
        env:
          GITHUB_TOKEN: ${{ steps.get_workflow_token.outputs.token }}
        run: |
          git config user.name "fuelviews-app[bot]"
          git config user.email "fuelviews-app[bot]@users.noreply.github.com"
          git add CHANGELOG.md
          git commit -m "chore: update changelog for ${{ steps.bump_version.outputs.new_tag }} [skip ci]"
          git push origin main

      - name: Release
        id: release
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ steps.get_workflow_token.outputs.token }}
        with:
          tag_name: ${{ steps.bump_version.outputs.new_tag }}
          body: ${{ steps.generate_release_notes.outputs.result }}
